services:
    app.diver_controller:
        class: AppBundle\Controller\DiverController
        arguments: ['@templating', '@app.certificate_service', '@app.diver_service', '@form.factory', '@session', '@router']

    app.dashboard_controller:
        class: AppBundle\Controller\DashboardController
        arguments: ['@templating', '@security.token_storage']

