services:
    app.security.forced_logout_listener:
       class: AppBundle\EventListener\ForcedLogoutListener
       arguments: [
         '@security.token_storage',
         '@security.authorization_checker',
         '@session',
         '@router',
         '@app.user_repository'
         ]
       tags:
           - name: kernel.event_listener
             event: kernel.request
             method: onKernelRequest
             priority: 0