services:
    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:User"]

    app.diver_repository:
        class: AppBundle\Repository\DiverRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:Diver"]

    app.certificate_repository:
        class: AppBundle\Repository\CertificateRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:Certificate"]

    app.specialty_repository:
        class: AppBundle\Repository\SpecialtyRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:Specialty"]

    app.equipment_repository:
        class: AppBundle\Repository\DivingGearRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:Gear"]

    app.divelog_repository:
        class: AppBundle\Repository\DiveLogRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:DiveLog"]
