services:
    app.diver_repository:
        class: AppBundle\Repository\DiverRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:Diver"]

    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:User"]