services:
    app.certificate_repository:
        class: AppBundle\Repository\CertificateRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:Certificate"]

    app.diver_repository:
        class: AppBundle\Repository\DiverRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:Diver"]

    app.specialty_repository:
        class: AppBundle\Repository\SpecialtyRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:Specialty"]

    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:User"]