services:
    app.diver_service:
        class: AppBundle\Service\DiverService
        arguments:
            - "@app.diver_repository"

    app.certificate_service:
        class: AppBundle\Service\CertificateService
        arguments:
            - "@app.certificate_repository"

    app.specialty_service:
        class: AppBundle\Service\SpecialtyService
        arguments:
            - "@app.specialty_repository"
