imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: controllers.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    #translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS user bundle Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: hank.kam@gmail.com
        sender_name: Hank Kam

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        css_sb_admin_2:
            inputs:
                - '@AppBundle/Resources/css/bootstrap/bootstrap.min.css'
                - '@AppBundle/Resources/css/sb-admin-2/plugins/metisMenu/metisMenu.min.css'
                - '@AppBundle/Resources/css/sb-admin-2/sb-admin-2.css'
                - '@AppBundle/Resources/css/sb-admin-2/plugins/dataTables.bootstrap.css'
                - '@AppBundle/Resources/css/responsive/responsive.dataTables.css'
                - '@AppBundle/Resources/css/font-awesome/font-awesome.min.css'
                - '@AppBundle/Resources/css/custom.css'

        js_sb_admin_2:
            inputs:
                - '@AppBundle/Resources/js/jquery/jquery-3.1.1.min.js'
                - '@AppBundle/Resources/js/bootstrap/bootstrap.min.js'
                - '@AppBundle/Resources/js/sb-admin-2/plugins/metisMenu/metisMenu.min.js'
                - '@AppBundle/Resources/js/sb-admin-2/plugins/dataTables/jquery.dataTables.min.js'
                - '@AppBundle/Resources/js/sb-admin-2/plugins/dataTables/dataTables.bootstrap.min.js'
                - '@AppBundle/Resources/js/sb-admin-2/plugins/dataTables/dataTables.responsive.js'
                - '@AppBundle/Resources/js/sb-admin-2/sb-admin-2.js'
                - '@AppBundle/Resources/js/custom.js'

        font-awesome-otf:
            inputs: '@AppBundle/Resources/fonts/font-awesome/FontAwesome.otf'
            output: 'fonts/FontAwesome.otf'

        font-awesome-eot:
            inputs: '@AppBundle/Resources/fonts/font-awesome/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'

        font-awesome-svg:
            inputs: '@AppBundle/Resources/fonts/font-awesome/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'

        font-awesome-ttf:
            inputs: '@AppBundle/Resources/fonts/font-awesome/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'

        font-awesome-woff:
            inputs: '@AppBundle/Resources/fonts/font-awesome/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'

        font-awesome-woff2:
            inputs: '@AppBundle/Resources/fonts/font-awesome/fontawesome-webfont.woff2'
            output: 'fonts/fontawesome-webfont.woff2'

        font-glyphicons-halflings-regular-eot:
            inputs: '@AppBundle/Resources/fonts/bootstrap/glyphicons-halflings-regular.eot'
            output: 'fonts/glyphicons-halflings-regular.eot'

        font-glyphicons-halflings-regular-svg:
            inputs: '@AppBundle/Resources/fonts/bootstrap/glyphicons-halflings-regular.svg'
            output: 'fonts/glyphicons-halflings-regular.svg'

        font-glyphicons-halflings-regular-ttf:
            inputs: '@AppBundle/Resources/fonts/bootstrap/glyphicons-halflings-regular.ttf'
            output: 'fonts/glyphicons-halflings-regular.ttf'

        font-glyphicons-halflings-regular-woff:
            inputs: '@AppBundle/Resources/fonts/bootstrap/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'

        font-glyphicons-halflings-regular-woff2:
            inputs: '@AppBundle/Resources/fonts/bootstrap/glyphicons-halflings-regular.woff2'
            output: 'fonts/glyphicons-halflings-regular.woff2'
