services:
    app.security_controller:
        class: AppBundle\Controller\SecurityController
        arguments: ['@templating', '@security.authentication_utils']

    form_factory_interface:
      class: Symfony\Component\Form\FormFactoryInterface

    app.registration_controller:
        class: AppBundle\Controller\RegistrationController
        arguments: ['@templating', '@app.registration_service', '@form.factory', '@session', '@router']



