services:
    app.member_repository:
        class: AppBundle\Repository\MemberRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:Member"]

    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle:User"]