## app/config/routing.yml
security_login:
    path:      /login
    defaults:  { _controller: app.security_controller:loginAction }
    methods: [GET, POST]

security_logout:
    path:      /logout

registration:
    path:      /register
    defaults:  { _controller: app.registration_controller:registerAction }
    methods: [GET, POST]
    requirements:
        username: \d+
        email: \d+
        plainPassword: \d+

dashboard:
    path:      /
    defaults:  { _controller: app.dashboard_controller:indexAction }
    methods: [GET]

member:
    path:      /member
    defaults:  { _controller: app.member_controller:allAction }
    methods: [GET]

member_create:
    path:      /member/add
    defaults:  { _controller: app.member_controller:addAction }
    methods: [POST]

member_get:
    path:      /member/{id}
    defaults:  { _controller: app.member_controller:getAction }
    methods: [GET]
    requirements:
        id: \d+

member_add:
    path:      /member/add
    defaults:  { _controller: app.member_controller:addAction }
    methods: [GET]

member_edit:
    path:      /member/{id}/edit
    defaults:  { _controller: app.member_controller:editAction }
    methods: [GET, POST]
    requirements:
        id: \d+
