fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

dashboard:
    path:      /
    defaults:  { _controller: app.dashboard_controller:indexAction }
    methods: [GET]

diver:
    path:      /diver
    defaults:  { _controller: app.diver_controller:allAction }
    methods: [GET]

diver_create:
    path:      /diver/add
    defaults:  { _controller: app.diver_controller:addAction }
    methods: [POST]

diver_get:
    path:      /diver/{id}
    defaults:  { _controller: app.diver_controller:getAction }
    methods: [GET]
    requirements:
        id: \d+

diver_add:
    path:      /diver/add
    defaults:  { _controller: app.diver_controller:addAction }
    methods: [GET]

diver_edit:
    path:      /diver/{id}/edit
    defaults:  { _controller: app.diver_controller:editAction }
    methods: [GET, POST]
    requirements:
        id: \d+

diver_log:
    path:      /diver/{id}/log
    defaults:  { _controller: app.divelog_controller:allAction }
    methods: [GET]
    requirements:
        id: \d+

